//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SClient.SServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SServiceReference.ISService")]
    public interface ISService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISService/Auth", ReplyAction="http://tempuri.org/ISService/AuthResponse")]
        void Auth(string clId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISService/GetChannels", ReplyAction="http://tempuri.org/ISService/GetChannelsResponse")]
        string[] GetChannels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISService/Connect", ReplyAction="http://tempuri.org/ISService/ConnectResponse")]
        void Connect(string chId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISService/Disconnect", ReplyAction="http://tempuri.org/ISService/DisconnectResponse")]
        void Disconnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISService/GetData", ReplyAction="http://tempuri.org/ISService/GetDataResponse")]
        double[] GetData();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISServiceChannel : SClient.SServiceReference.ISService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SServiceClient : System.ServiceModel.ClientBase<SClient.SServiceReference.ISService>, SClient.SServiceReference.ISService {
        
        public SServiceClient() {
        }
        
        public SServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Auth(string clId) {
            base.Channel.Auth(clId);
        }
        
        public string[] GetChannels() {
            return base.Channel.GetChannels();
        }
        
        public void Connect(string chId) {
            base.Channel.Connect(chId);
        }
        
        public void Disconnect() {
            base.Channel.Disconnect();
        }
        
        public double[] GetData() {
            return base.Channel.GetData();
        }
    }
}
